FROM python:3.7-slim

RUN BUILD_DEPS='gcc libc-dev libmariadb-dev-compat' \
    && apt-get update \
    && apt-get install -y --no-install-recommends $BUILD_DEPS

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-warn-script-location --prefix /app/local -r requirements.txt
COPY . /app

ENV PATH=/app/local/bin:$PATH PYTHONPATH=/app/local/lib/python3.7/site-packages
