FROM python:3.7-slim

RUN RUN_DEPS='libmariadb3' \
    && apt-get update \
    && apt-get install -y --no-install-recommends $RUN_DEPS

WORKDIR /app
COPY --from=builder /app /app

ENV PATH=/app/local/bin:$PATH PYTHONPATH=/app/local/lib/python3.7/site-packages
