# Generated by Django 3.0.5 on 2020-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prober',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=255)),
                ('added', models.DateTimeField()),
            ],
            options={
                'db_table': 'prober',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProberTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=4)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('added', models.DateTimeField()),
            ],
            options={
                'db_table': 'prober_target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrcDst',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('dst', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'src_dst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('ping_schema', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'version',
                'managed': False,
            },
        ),
    ]
