# Generated by Django 3.0.5 on 2020-04-15 18:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prober',
            options={},
        ),
        migrations.AlterModelOptions(
            name='probertarget',
            options={},
        ),
        migrations.AlterModelOptions(
            name='srcdst',
            options={},
        ),
        migrations.AlterField('SrcDst', 'dst', models.GenericIPAddressField(protocol='IPv4'))
    ]
