# Generated by Django 3.0.5 on 2020-04-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0002_auto_20200415_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='probertarget',
            name='prober',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pingweb.Prober'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srcdst',
            name='prober',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pingweb.Prober'),
            preserve_default=False,
        ),
    ]
