# Generated by Django 3.0.5 on 2020-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0003_auto_20200418_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prober',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
