# Generated by Django 3.0.5 on 2020-06-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0005_collectormessage_serversetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='probertarget',
            name='prober',
        ),
        migrations.AlterField(
            model_name='probertarget',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='probertarget',
            name='ip',
            field=models.CharField(max_length=39),
        ),
        migrations.CreateModel(
            name='ProbeGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('probers', models.ManyToManyField(to='pingweb.Prober')),
                ('targets', models.ManyToManyField(to='pingweb.Target')),
            ],
        ),
    ]
