# Generated by Django 3.0.5 on 2020-06-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0006_auto_20200624_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probertarget',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='IP Address'),
        ),
    ]
