# Generated by Django 3.0.5 on 2020-06-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0007_auto_20200624_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probertarget',
            name='type',
            field=models.CharField(choices=[('ICMP', 'ICMP')], default='ICMP', max_length=4),
        ),
    ]
