# Generated by Django 3.0.5 on 2020-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0008_auto_20200627_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probertarget',
            name='type',
            field=models.CharField(choices=[('icmp', 'ICMP')], default='icmp', max_length=4),
        ),
    ]
