# Generated by Django 3.0.5 on 2020-06-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0009_reordered_10_20200627_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prober',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='probertarget',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
