# Generated by Django 3.0.5 on 2020-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0009_reordered_20_20200627_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prober',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
