# Generated by Django 3.0.5 on 2020-07-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0010_auto_20200627_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probegroup',
            name='probers',
            field=models.ManyToManyField(blank=True, to='pingweb.Prober'),
        ),
        migrations.AlterField(
            model_name='probegroup',
            name='targets',
            field=models.ManyToManyField(blank=True, to='pingweb.ProberTarget'),
        ),
    ]
