# Generated by Django 3.0.5 on 2020-07-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0011_auto_20200701_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProberTarget',
            new_name='Target',
        ),
    ]
