# Generated by Django 3.0.5 on 2020-07-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingweb', '0012_auto_20200701_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
